// @ts-nocheck
// GENERATED by scripts/sync-mathpad.mjs from ../webassign-mathpad.user.js. Do not edit.
const NS = 'http://www.w3.org/1998/Math/MathML';
const EMPTY = `<math xmlns="${NS}"/>`;
    // Symbol tables — every entry mirrors the MathML the real pad buttons emit.

    const TRIG = [
        'sin', 'cos', 'tan', 'csc', 'sec', 'cot',
        'arcsin', 'arccos', 'arctan', 'arccsc', 'arcsec', 'arccot',
        'sinh', 'cosh', 'tanh', 'csch', 'sech', 'coth',
        'arcsinh', 'arccosh', 'arctanh', 'arccsch', 'arcsech', 'arccoth',
    ];
    const TRIG_ALIAS = {
        asin: 'arcsin', acos: 'arccos', atan: 'arctan', acsc: 'arccsc', asec: 'arcsec', acot: 'arccot',
        asinh: 'arcsinh', acosh: 'arccosh', atanh: 'arctanh', acsch: 'arccsch', asech: 'arcsech', acoth: 'arccoth',
    };
    const LOGS = ['log', 'ln'];
    const SPECIAL_FUNCS = ['sqrt', 'cbrt', 'root', 'abs', 'exp', 'vec', 'hat', 'arrow'];

    // Lowercase greek -> <mi>, as the Greek tab emits. Note: pad "phi" is U+03D5.
    const GREEK_LOWER = {
        alpha: 'α', beta: 'β', gamma: 'γ', delta: 'δ', epsilon: 'ε', zeta: 'ζ', eta: 'η', theta: 'θ',
        iota: 'ι', kappa: 'κ', lambda: 'λ', mu: 'μ', nu: 'ν', xi: 'ξ', omicron: 'ο', pi: 'π', rho: 'ρ',
        sigma: 'σ', tau: 'τ', upsilon: 'υ', phi: 'ϕ', varphi: 'φ', chi: 'χ', psi: 'ψ', omega: 'ω',
    };
    // Capital greek -> <mo>, as the Greek tab's "More" panel emits.
    const GREEK_UPPER = {
        Alpha: 'Α', Beta: 'Β', Gamma: 'Γ', Delta: 'Δ', Epsilon: 'Ε', Zeta: 'Ζ', Eta: 'Η', Theta: 'Θ',
        Iota: 'Ι', Kappa: 'Κ', Lambda: 'Λ', Mu: 'Μ', Nu: 'Ν', Xi: 'Ξ', Omicron: 'Ο', Pi: 'Π', Rho: 'Ρ',
        Sigma: 'Σ', Tau: 'Τ', Upsilon: 'Υ', Phi: 'Φ', Chi: 'Χ', Psi: 'Ψ', Omega: 'Ω',
    };
    const CONST_WORDS = {
        inf: () => mo('∞'), infinity: () => mo('∞'), oo: () => mo('∞'),
        DNE: () => mtext('DNE'),
        undefined: () => mtext('UNDEFINED'), UNDEFINED: () => mtext('UNDEFINED'),
        nosolution: () => mtext('NO SOLUTION'), NOSOLUTION: () => mtext('NO SOLUTION'),
        empty: () => mo('∅'), emptyset: () => mo('∅'),
        deg: () => mo('°'),
        hbar: () => mi('ℏ'),
    };
    const INFIX_WORDS = { union: '∪', cup: '∪', intersect: '∩', cap: '∩' };

    // `#name` escapes for buttons that have no natural typed form.
    const HASH = {
        i: () => mi('\u{1D5F6}'), j: () => mi('\u{1D5F7}'), k: () => mi('\u{1D5F8}'), // Vectors tab bold i/j/k
        im: () => mi('i', ' mathvariant="normal"'),                                   // "Imaginary number i"
        deg: () => mo('°'), empty: () => mo('∅'), inf: () => mo('∞'), pi: () => mi('π'),
        dne: () => mtext('DNE'), undef: () => mtext('UNDEFINED'), nosol: () => mtext('NO SOLUTION'),
    };

    // Infix operators (output as a flat <mo>). Values are what the pad emits.
    const INFIX = {
        '+': '+', '-': '-', '−': '-', '=': '=', '<': '<', '>': '>',
        '<=': '≤', '≤': '≤', '>=': '≥', '≥': '≥', '!=': '≠', '≠': '≠',
        ',': ',', ';': ';', ':': ':', '->': '→', '→': '→', '÷': '÷',
        '∪': '∪', '∩': '∩', '⇀': '⇀', '⇌': '⇌', '←': '←',
    };
    const TIMES = ['*', '⋅', '·', '×', '.'];
    // Single unicode characters that act as a value.
    const SYMBOL_CHARS = { 'π': () => mi('π'), '∞': () => mo('∞'), '°': () => mo('°'), '∅': () => mo('∅'), 'ℏ': () => mi('ℏ') };

    const WORDS = [
        ...TRIG, ...Object.keys(TRIG_ALIAS), ...LOGS, ...SPECIAL_FUNCS,
        ...Object.keys(GREEK_LOWER), ...Object.keys(GREEK_UPPER), ...Object.keys(CONST_WORDS), ...Object.keys(INFIX_WORDS),
    ].sort((a, b) => b.length - a.length);

    // ---------------------------------------------------------------------------
    // MathML node helpers. A node is { x: xml, multi?: bool, paren?: node }.
    // `multi` means x is several sibling elements (needs <mrow> inside a slot);
    // `paren` is set on plain (...) groups so they can be unwrapped in / ^ _ sqrt.
    // ---------------------------------------------------------------------------

    const escXml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const enc = (s) => [...s].map((c) => (c.codePointAt(0) > 126
        ? `&#x${c.codePointAt(0).toString(16).toUpperCase()};` : escXml(c))).join('');

    const mi = (s, attrs = '') => ({ x: `<mi${attrs}>${enc(s)}</mi>` });
    const mo = (s) => ({ x: `<mo>${enc(s)}</mo>`, op: s });
    const mtext = (s) => ({ x: `<mtext>${enc(s)}</mtext>` });
    const xmlOf = (nodes) => nodes.map((n) => n.x).join('');
    const group = (nodes) => (nodes.length === 1 ? nodes[0] : { x: xmlOf(nodes), multi: nodes.length > 1 });
    const slot = (n) => (n.multi ? `<mrow>${n.x}</mrow>` : (n.x || '<mrow/>'));
    const row = (n) => (n.x ? `<mrow>${n.x}</mrow>` : '<mrow/>');
    const strip = (n) => n.paren || n;
    const concat = (...ns) => ({ x: ns.map((n) => n.x).join(''), multi: true });

    function number(v) {
        // The pad splits typed decimals: 12.5 -> <mn>12</mn><mo>.</mo><mn>5</mn>
        const out = [];
        v.split(/(\.)/).forEach((p) => {
            if (p === '.') out.push(mo('.'));
            else if (p) out.push({ x: `<mn>${p}</mn>` });
        });
        return group(out);
    }

    // ---------------------------------------------------------------------------
    // Tokenizer
    // ---------------------------------------------------------------------------

    const TWO_CHAR = ['<=', '>=', '!=', '->', '**'];

    function splitWord(run) {
        const out = [];
        let i = 0;
        while (i < run.length) {
            const w = WORDS.find((word) => run.startsWith(word, i));
            if (w) { out.push({ k: 'word', v: w }); i += w.length; }
            else { out.push({ k: 'letter', v: run[i] }); i += 1; }
        }
        return out;
    }

    function tokenize(src) {
        const t = [];
        let i = 0;
        while (i < src.length) {
            const c = String.fromCodePoint(src.codePointAt(i));
            if (/\s/.test(c)) { i += c.length; continue; }
            if (/[0-9]/.test(c) || (c === '.' && /[0-9]/.test(src[i + 1] || ''))) {
                let j = i;
                while (j < src.length && /[0-9.]/.test(src[j])) j++;
                t.push({ k: 'num', v: src.slice(i, j) });
                i = j;
                continue;
            }
            if (/[A-Za-z]/.test(c)) {
                let j = i;
                while (j < src.length && /[A-Za-z]/.test(src[j])) j++;
                t.push(...splitWord(src.slice(i, j)));
                i = j;
                continue;
            }
            if (c === '"') {
                const j = src.indexOf('"', i + 1);
                if (j < 0) throw new SyntaxError('Unclosed "text"');
                t.push({ k: 'text', v: src.slice(i + 1, j) });
                i = j + 1;
                continue;
            }
            if (c === '#') {
                let j = i + 1;
                while (j < src.length && /[A-Za-z]/.test(src[j])) j++;
                t.push({ k: 'hash', v: src.slice(i + 1, j) });
                i = j;
                continue;
            }
            const two = src.slice(i, i + 2);
            if (TWO_CHAR.includes(two)) { t.push({ k: 'op', v: two }); i += 2; continue; }
            t.push({ k: 'op', v: c });
            i += c.length;
        }
        return t;
    }

    // ---------------------------------------------------------------------------
    // Parser: text -> MathML body (without the <math> wrapper)
    // ---------------------------------------------------------------------------

    function parse(src) {
        const toks = tokenize(String(src));
        let pos = 0;
        const peek = () => toks[pos];
        const next = () => toks[pos++];
        const isOp = (tk, v) => tk && tk.k === 'op' && tk.v === v;
        const fail = (msg) => { throw new SyntaxError(`${msg} (at token ${pos + 1} of "${src}")`); };
        const expect = (v) => { if (!isOp(peek(), v)) fail(`Expected "${v}"`); next(); };

        // Flat sequence of runs separated by infix operators, until a closer.
        function parseSeq(closers) {
            const out = [];
            let operandPos = true;
            for (;;) {
                const tk = peek();
                if (!tk) {
                    if (closers.length) fail(`Missing closing ${closers.join(' or ')}`);
                    break;
                }
                if (tk.k === 'op') {
                    if (tk.v === '>=' && closers.includes('>')) {
                        // "<a,b>=c": split into closing ">" and "="
                        toks.splice(pos, 1, { k: 'op', v: '>' }, { k: 'op', v: '=' });
                        break;
                    }
                    if (closers.includes(tk.v) && !(operandPos && tk.v === '|')) break;
                    if (')]}⟩'.includes(tk.v)) fail(`Unexpected "${tk.v}"`);
                    if (INFIX[tk.v] && !(operandPos && tk.v === '<')) {
                        next();
                        out.push(mo(INFIX[tk.v]));
                        operandPos = true;
                        continue;
                    }
                }
                if (tk.k === 'word' && INFIX_WORDS[tk.v]) {
                    next();
                    out.push(mo(INFIX_WORDS[tk.v]));
                    operandPos = true;
                    continue;
                }
                const run = parseRun(closers);
                if (!run.length) fail(`Unexpected "${tk.v}"`);
                out.push(...run);
                operandPos = false;
            }
            return out;
        }

        // A run of factors joined by implicit/explicit multiplication and "/".
        // "/" takes everything in the run so far as numerator and one factor as
        // denominator, which matches left-to-right evaluation: 1/2x = (1/2)x.
        function parseRun(closers) {
            let run = [];
            for (;;) {
                const tk = peek();
                if (!tk) break;
                if (tk.k === 'op') {
                    if (TIMES.includes(tk.v)) {
                        if (!run.length) fail(`Nothing before "${tk.v}"`);
                        next();
                        run.push(mo('⋅'));
                        continue;
                    }
                    if (tk.v === '/') {
                        if (!run.length) fail('Nothing before "/"');
                        next();
                        const num = strip(group(run));
                        const den = strip(parseSigned(closers));
                        run = [{ x: `<mfrac>${slot(num)}${slot(den)}</mfrac>` }];
                        continue;
                    }
                    const afterTimes = !run.length || run[run.length - 1].op === '⋅';
                    if (!startsFactor(tk, closers, afterTimes)) break;
                } else if (tk.k === 'word' && INFIX_WORDS[tk.v]) {
                    break;
                }
                run.push(parsePostfix(closers));
            }
            return run;
        }

        function startsFactor(tk, closers, atStart) {
            const v = tk.v;
            if ('([{⟨√'.includes(v)) return true;
            if (v === '|') return !closers.includes('|');
            if (v === '<') return atStart;
            if (SYMBOL_CHARS[v]) return true;
            return /\p{L}/u.test(v);
        }

        function parseSigned(closers) {
            const tk = peek();
            if (isOp(tk, '-') || isOp(tk, '+') || isOp(tk, '−')) {
                next();
                return concat(mo(tk.v === '+' ? '+' : '-'), parsePostfix(closers));
            }
            return parsePostfix(closers);
        }

        function scripts() {
            let sub = null;
            let sup = null;
            for (;;) {
                const tk = peek();
                if (isOp(tk, '_') && !sub) { next(); sub = parseScript(false); continue; }
                if ((isOp(tk, '^') || isOp(tk, '**')) && !sup) { next(); sup = parseScript(true); continue; }
                return { sub, sup };
            }
        }

        function attach(base, { sub, sup }) {
            if (sub && sup) return { x: `<msubsup>${slot(base)}${slot(sub)}${slot(sup)}</msubsup>` };
            if (sub) return { x: `<msub>${slot(base)}${slot(sub)}</msub>` };
            if (sup) return { x: `<msup>${slot(base)}${slot(sup)}</msup>` };
            return base;
        }

        function parsePostfix(closers) {
            let base = attach(parseAtom(closers), scripts());
            while (isOp(peek(), '!') || isOp(peek(), "'")) base = concat(base, mo(next().v));
            return base;
        }

        // Exponent / subscript: a (group), or [sign] atom, with right-assoc ^.
        function parseScript(isSup) {
            let sign = null;
            if (isOp(peek(), '-') || isOp(peek(), '+') || isOp(peek(), '−')) sign = next().v === '+' ? '+' : '-';
            let a = strip(parseAtom([]));
            if (isSup && (isOp(peek(), '^') || isOp(peek(), '**'))) {
                next();
                a = { x: `<msup>${slot(a)}${slot(parseScript(true))}</msup>` };
            }
            return sign ? concat(mo(sign), a) : a;
        }

        function fence(open, closers) {
            const nodes = parseSeq(closers);
            const close = next().v;
            const inner = group(nodes);
            const body = row(inner);
            const pair = open + close;
            const attrs = {
                '()': '',
                '(]': ' close="]" separators=""',
                '[]': ' open="[" close="]"',
                '[)': ' open="[" separators=""',
                '{}': ' open="{" close="}"',
                '<>': ' open="&lt;" close="&gt;"', '<⟩': ' open="&lt;" close="&gt;"',
                '⟨>': ' open="&lt;" close="&gt;"', '⟨⟩': ' open="&lt;" close="&gt;"',
                '||': ' open="|" close="|"',
            }[pair];
            const node = { x: `<mfenced${attrs}>${body}</mfenced>` };
            if (pair === '()') node.paren = nodes.length ? inner : { x: '' };
            return node;
        }

        // Argument of a function: (…) contents, or a single factor.
        function fnArg(closers) {
            if (isOp(peek(), '(')) {
                next();
                const nodes = parseSeq([')']);
                expect(')');
                return group(nodes);
            }
            return strip(parsePostfix(closers));
        }

        function splitArgs(nodes) {
            const args = [[]];
            nodes.forEach((n) => (n.op === ',' ? args.push([]) : args[args.length - 1].push(n)));
            return args.map(group);
        }

        function word(w, closers) {
            const name = TRIG_ALIAS[w] || w;
            if (TRIG.includes(name) || LOGS.includes(name)) {
                const head = attach(mi(name), scripts());
                const arg = fnArg(closers);
                const attrs = TRIG.includes(name) ? ' separators=""' : '';
                return concat(head, { x: `<mfenced${attrs}>${row(arg)}</mfenced>` });
            }
            switch (name) {
                case 'sqrt': {
                    const a = fnArg(closers);
                    return { x: a.x ? `<msqrt>${a.x}</msqrt>` : '<msqrt/>' };
                }
                case 'cbrt':
                    return { x: `<mroot>${slot(fnArg(closers))}<mn>3</mn></mroot>` };
                case 'root': {
                    expect('(');
                    const args = splitArgs(parseSeq([')']));
                    expect(')');
                    if (args.length === 2) return { x: `<mroot>${slot(args[1])}${slot(args[0])}</mroot>` };
                    if (args.length === 1 && isOp(peek(), '(')) {
                        // root(n)(x)
                        return { x: `<mroot>${slot(fnArg(closers))}${slot(args[0])}</mroot>` };
                    }
                    if (args.length === 1) return { x: `<msqrt>${args[0].x}</msqrt>` };
                    return fail('root takes (index, radicand)');
                }
                case 'abs':
                    return { x: `<mfenced open="|" close="|">${row(fnArg(closers))}</mfenced>` };
                case 'exp':
                    return { x: `<msup><mi>e</mi>${slot(fnArg(closers))}</msup>` };
                case 'vec':
                    return { x: `<mover>${slot(fnArg(closers))}<mo>&#x21C0;</mo></mover>` };
                case 'arrow':
                    return { x: `<mover>${slot(fnArg(closers))}<mo>&#x2192;</mo></mover>` };
                case 'hat':
                    return { x: `<mover>${slot(fnArg(closers))}<mo>^</mo></mover>` };
                default:
            }
            if (GREEK_LOWER[name]) return mi(GREEK_LOWER[name]);
            if (GREEK_UPPER[name]) return mo(GREEK_UPPER[name]);
            if (CONST_WORDS[name]) return CONST_WORDS[name]();
            return fail(`Unknown word "${w}"`);
        }

        function parseAtom(closers) {
            const tk = next();
            if (!tk) return fail('Unexpected end of input');
            switch (tk.k) {
                case 'num': return number(tk.v);
                case 'letter': return mi(tk.v);
                case 'text': return mtext(tk.v);
                case 'hash':
                    if (!HASH[tk.v]) fail(`Unknown #${tk.v} (have: ${Object.keys(HASH).map((k) => '#' + k).join(' ')})`);
                    return HASH[tk.v]();
                case 'word': return word(tk.v, closers);
                default:
            }
            const v = tk.v;
            if (v === '(') return fence('(', [')', ']']);
            if (v === '[') return fence('[', [']', ')']);
            if (v === '{') return fence('{', ['}']);
            if (v === '<' || v === '⟨') return fence(v, ['>', '⟩']);
            if (v === '|') return fence('|', ['|']);
            if (v === '√') {
                const a = strip(parsePostfix(closers));
                return { x: `<msqrt>${a.x}</msqrt>` };
            }
            if (SYMBOL_CHARS[v]) return SYMBOL_CHARS[v]();
            if (/[Α-Ω]/.test(v)) return mo(v);
            if (/\p{L}/u.test(v)) return mi(v);
            return fail(`Unexpected "${v}"`);
        }

        const out = parseSeq([]);
        return xmlOf(out);
    }

    // ---------------------------------------------------------------------------
    // MathML -> typeable text (for reading answers back)
    // ---------------------------------------------------------------------------

    const REV_MO = { '⋅': '*', '≤': '<=', '≥': '>=', '≠': '!=', '→': '->', '∞': 'inf', '∅': 'empty', '°': 'deg', '∪': ' union ', '∩': ' intersect ', '÷': '÷' };
    const REV_MI = Object.assign(
        { '\u{1D5F6}': '#i', '\u{1D5F7}': '#j', '\u{1D5F8}': '#k', 'ℏ': 'hbar' },
        ...Object.entries(GREEK_LOWER).map(([k, v]) => ({ [v]: k })),
        ...Object.entries(GREEK_UPPER).map(([k, v]) => ({ [v]: k })),
    );
    const REV_TEXT = { DNE: 'DNE', UNDEFINED: 'undefined', 'NO SOLUTION': 'nosolution' };

    function toText(mathml) {
        const doc = new DOMParser().parseFromString(mathml || EMPTY, 'application/xml');
        const kids = (n) => [...n.children];
        const atomic = (n) => ['mi', 'mn', 'mo', 'mtext', 'mfenced', 'msqrt', 'mroot'].includes(n.localName)
            || (n.localName === 'mrow' && n.children.length === 1 && atomic(n.children[0]));
        const wrap = (n) => (atomic(n) ? tt(n) : `(${tt(n)})`);
        function tt(n) {
            const k = kids(n);
            const all = () => k.map(tt).join('');
            const txt = n.textContent;
            switch (n.localName) {
                case 'math': case 'mrow': case 'maction': case 'mstyle': return all();
                case 'mn': return txt;
                case 'mi':
                    if (n.getAttribute('mathvariant') === 'normal' && txt === 'i') return '#im';
                    return REV_MI[txt] || txt;
                case 'mo': return REV_MO[txt] || REV_MI[txt] || (txt === ',' ? ', ' : txt);
                case 'mtext': return REV_TEXT[txt] || `"${txt}"`;
                case 'mfrac': return `${wrap(k[0])}/${wrap(k[1])}`;
                case 'msup': return `${wrap(k[0])}^${wrap(k[1])}`;
                case 'msub': return `${wrap(k[0])}_${wrap(k[1])}`;
                case 'msubsup': return `${wrap(k[0])}_${wrap(k[1])}^${wrap(k[2])}`;
                case 'msqrt': return `sqrt(${all()})`;
                case 'mroot': return `root(${tt(k[1])}, ${tt(k[0])})`;
                case 'mover': {
                    const acc = k[1] ? k[1].textContent : '';
                    const fn = { '⇀': 'vec', '→': 'arrow', '^': 'hat' }[acc] || 'vec';
                    return `${fn}(${tt(k[0])})`;
                }
                case 'mfenced': {
                    let open = n.hasAttribute('open') ? n.getAttribute('open') : '(';
                    let close = n.hasAttribute('close') ? n.getAttribute('close') : ')';
                    if (open === '<') { open = '<'; close = '>'; }
                    return `${open}${all()}${close}`;
                }
                default: return all();
            }
        }
        return tt(doc.documentElement).replace(/\s+/g, ' ').trim();
    }

    // ---------------------------------------------------------------------------

export const toMathML = (expr) => `<math xmlns="${NS}">${parse(expr)}</math>`;
export { parse, toText, NS, EMPTY, TRIG, TRIG_ALIAS, LOGS, SPECIAL_FUNCS, GREEK_LOWER, GREEK_UPPER, CONST_WORDS, HASH };
