// Generates src/lib/mathpad.js from the userscript so the parser has one source of truth.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const src = readFileSync(here('../../webassign-mathpad.user.js'), 'utf8');
const start = src.indexOf('    // Symbol tables');
const end = src.indexOf('    // Page integration');
if (start < 0 || end < 0) throw new Error('Markers not found in webassign-mathpad.user.js');
const body = src.slice(src.lastIndexOf('\n', start - 1) + 1, src.lastIndexOf('\n', end - 1) + 1)
    .replace(/^ {4}\/\/ -{10,}\n$/m, '');

const out = `// @ts-nocheck
// GENERATED by scripts/sync-mathpad.mjs from ../webassign-mathpad.user.js. Do not edit.
const NS = 'http://www.w3.org/1998/Math/MathML';
const EMPTY = \`<math xmlns="\${NS}"/>\`;
${body}
export const toMathML = (expr) => \`<math xmlns="\${NS}">\${parse(expr)}</math>\`;
export { parse, toText, NS, EMPTY, TRIG, TRIG_ALIAS, LOGS, SPECIAL_FUNCS, GREEK_LOWER, GREEK_UPPER, CONST_WORDS, HASH };
`;
writeFileSync(here('../src/lib/mathpad.js'), out);
console.log('src/lib/mathpad.js written');
